

INSERT INTO BOOK_LEND_RECORD (BOOK_ID,KEEPER_ID,LEND_DATE )
		      VALUES(2004, '0002', GETDATE())
UPDATE BOOK_LEND_RECORD
SET LEND_DATE='2019-01-02 00:00:00:00'
WHERE KEEPER_ID=0002
SELECT bd.BOOK_ID as [書本ID],
			  FORMAT( bd.BOOK_BOUGHT_DATE, 'd', 'zh-TW') AS [購書日期],
			  REPLACE( FORMAT( blr.LEND_DATE, 'd', 'KO-KR') ,'-','/') AS [借閱日期],
			  bcl.BOOK_CLASS_ID+ '-' +bcl.BOOK_CLASS_NAME AS [書籍類別],
			  blr.KEEPER_ID+'-'+ mm.USER_CNAME+'('+mm.USER_ENAME+')' AS [借閱人],
			  bd.BOOK_STATUS+'-'+bco.CODE_NAME AS [狀態] ,
			  REPLACE(CONVERT(VARchar(20),CAST(bd.BOOK_AMOUNT AS money),1),'.00','')+'元'  AS [購書金額]
FROM BOOK_LEND_RECORD AS  blr
LEFT JOIN BOOK_DATA AS bd 
		ON blr.BOOK_ID = bd.BOOK_ID
LEFT JOIN BOOK_CLASS AS bcl
		ON bd.BOOK_CLASS_ID = bcl.BOOK_CLASS_ID
LEFT JOIN BOOK_CODE AS bco
		ON  bd.BOOK_STATUS= bco.CODE_ID
LEFT JOIN MEMBER_M AS mm
		ON mm.USER_ID=blr.KEEPER_ID

WHERE blr.KEEPER_ID=0002
ORDER BY bd.BOOK_AMOUNT DESC